Update smeem-release.yml

diff --git a/.github/workflows/smeem-release.yml b/.github/workflows/smeem-release.yml
--- a/.github/workflows/smeem-release.yml
+++ b/.github/workflows/smeem-release.yml
@@ -67,10 +67,16 @@ jobs:
         UUID=`/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i ./$PROVISION)`
         cp "./$PROVISION" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
         done
+    - name: Check if archive exists
+      run: |
+        if [ ! -d "$XC_ARCHIVE_PATH" ]; then
+          echo "Archive not found at $XC_ARCHIVE_PATH"
+          exit 1
+        fi
     - name: Archive app
       run: |
         mkdir artifacts
-        xcodebuild archive -project Smeem-iOS/Smeem-iOS.xcodeproj -scheme Smeem-Release -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
+        xcodebuild archive -project Smeem-iOS/Smeem-iOS.xcodeproj -scheme Smeem-Release -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' -archivePath "$XC_ARCHIVE_PATH"
     - name: Export app
       run: xcodebuild -exportArchive -archivePath "$XC_ARCHIVE_PATH" -exportOptionsPlist .github/ExportOptions.plist -exportPath "$XC_EXPORT_PATH"
     - name: Upload app to TestFlight
